services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      DISK_SIZE: "256G"
       RAM_SIZE: "12G"
       CPU_CORES: "4"
       DISK2_SIZE: "32G"
       DISK3_SIZE: "64G"
        USERNAME: "Fivem"
        PASSWORD: "Fivem"
        
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
